### ISSUE TITLE
I need advice/help uploading the Pedigree Editor zip file into REDCap without a CSV format?

### ISSUE THREAD

**Issue by juliewilliamsdada2** [aehrc/redcap_pedigree_editor#3]
Hi, I opened a github account, downloaded Pedigree Editor and all of its update plug ins, but cannot upload the Master file nor any cloned versions into REDCap which rejects the upload for not having a file of the format "instrument.CSV" in the ZIP download. What steps should I be taking to download this Pedigree Editor in a format that REDCap will recognize? I tried inserting v before the version number, cloning and CMD git commands to format it correctly....what am I missing here? Seems self explanatory through your instructions yet it is not.
Thanks

**Comment by juliewilliamsdada2** [comment]
Hello???

**Comment by dconlan** [comment]
@juliewilliamsdada2 I'm really sorry, some how my github account decided I should not be notified about issues in my projects :(

I suspect a year later you have already sorted things out or given up on the tool.

I've never seen issues with instrument.csv before.

If you go to this page you will see the latest release
https://github.com/aehrc/redcap_pedigree_editor/releases/tag/v0.3.2


If you download the zip version it should give you a file called redcap_pedigree_editor-0.3.2.zip

This file is unzipped into your REDCap external modules directory found at redcap/modules but it will create a directory called 
redcap_pedigree_editor-0.3.2, which is the wrong naming format. rename that directory to redcap_pedigree_editor_v0.3.2.

Once this is done you can go to the external module configuration inside REDCap and use enable module to select and enable the module.

**Comment by juliewilliamsdada2** [comment]
Hi David!! Thanks so much for the reply back! It’s still actually a work in progress for us, integrating Pedigree Editor into our instance of REDCap. We asked the creators of REDCap at Vanderbilt University Medical Center, in Nashville TN, to enable your software as an external module! It is up and running and my prior-mentioned CSV questions are resolved, thank you.
Have you ever worked with developing a REDCap Survey that can pipe JSON code right into Pedigree Editor to generate a pedigree diagram from survey answers? I’ve built out the instruments I need, to correlate to positions on a three-generation pedigree, but am stuck as to how to interpret the JSON code required for each position. If you would be willing to enlighten me on this, or point me to a programmer who would, I would be ever so grateful!!
  FYI, the Hereditary Cancer Center at Vanderbilt University where REDCap was created in 2007 houses one of the longest running cancer registries in the U.S., partnered with Sloan-Kettering in New York to expand internationally into Europe just this year. I mention this, because I have told the director of the Vanderbilt Cancer Registry about your Pedigree Editor and they are HIGLY interested in adopting it, should I get a REDCap Survey up and running to demonstrate for them. Currently, they use BODACEA alongside REDCap but cannot store pedigrees inside REDCap as they wish to.
 So ANY help you can provide to advise me as I develop the correlation between my survey and PE in JSON would be greatly appreciated, and could potentially perpetuate your influence via PE into global cancer research in a major way(!!) I am merely a genetic counselor working for a rare disease non-profit, but would love to collaborate to help make this happen. It would benefit so many patients internationally…

Thanks for your time and reply!
Julie

Julie Williams, MS CGC
Research Engagement Director
the DADA2 Foundation
htts://dada2.org

P.S. I attached a short PPT deck I slapped together to show our collaborators, that shows examples of our REDCap Survey format

**Comment by dconlan** [comment]
@juliewilliamsdada2

Hi Julie,

 I don't think github passed along your power point. 

I have done quite a bit of work on making this plugin integrate better with REDCap. I have not done an official release of the changes because I'm still not happy with it.

The major change I made was to allow the addition of action tags to link a field in a instrument with a field in the pedigree.

So an action tag of `@PEDIGREE_TAG=proband_first_name` would mark a field as being the first name of the proband. The external module would then use this to prepopulate the pedigree diagram when it was first opened. It would also attempt to update the fields in the form with any changed values when the pedigree was saved back into REDCap.

Here are my issues and the main reason I've not released a new version:
1. Each possible person in the tree needs its own set of fields in REDCap. The people I was working with wanted to allow up to 20 children, with each allowing up to 6 conditions and associated phenotypes and genes. This many fields pretty much kills REDCap.  The project we built to house the data contained more than 2000 fields and included a stack of logic to show/hide fields. Basically it ran like a dog. The suggested maximum number of fields for a single form is 500. In theory we can split the 2000 fields up across multiple forms, say one for each generation, but the write back into redcap mechanism can only change fields in the current form. To deal with updating fields in previous forms I will need to hook the save and manually change the entries in the database for the earlier forms. I've not attempted this yet.
2. REDCap has no 'official' way of updating a field in a form in javascript. I can poke things in, but the next version of REDCap may decide they will tweak their naming conventions for form elements and then the code will break. Because there is so many fields and lots of logic to show/hide based on what data is in the tree, it can be very difficult to update the fields in the correct order. I found on some occasions the branching logic would be applied before all the fields were updated and give the user an error about a field having a value when it is not reachable. It would then remove the value.

There is some documentation about the fhir format used to store the data here:
https://github.com/aehrc/redcap_pedigree_editor/blob/master/open-pedigree/FHIR_Format.md

I am happy to take this discussion out of github, I can try and set you up a demo of the current state of the plugin and discuss the features that could help you accomplish your goals. Send me a mail at david.conlan@csiro.au

David Conlan
